root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/bin/main"
  cmd = "templ generate && go build -o ./tmp/bin/main ./cmd/blog/main.go"
  delay = 1000
  exclude_dir = ["pgdata", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go", "input.css"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "md"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true
  proxy_port = 8383
  app_port = 8080
