version: '3'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: go-blog
    environment:
      - POSTGRES_USER="blog"
      - POSTGRES_PASSWORD=""
      - POSTGRES_PORT=5432
      - POSTGRES_DB="posts"

  postgres:
    image: postgres:bookworm
    name: go-blog-db
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER="blog"
      - POSTGRES_PASSWORD=""
      - POSTGRES_PORT=5432
      - POSTGRES_DB="posts"

volumes:
  pg-data:
