version: '3'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: go-blog
    environment:
      DATABASE_URL: postgresql://blog:blog@db:5432/posts

  postgres:
    image: postgres:bookworm
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgressql/data
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog

volumes:
  pg-data:
