version: '3'

services:
  blog:
    image: go-blog:sr9wvrl7v05kqc91p441px3lpj102l8m
    restart: unless-stopped
    container_name: go-blog
    ports:
      - 8042:8080
    environment:
      DATABASE_URL: postgresql://blog:blog@db:5432/blog

  postgres:
    image: postgres:bookworm
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog

volumes:
  pg-data:
